# Generated by Django 3.2.6 on 2021-08-20 14:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('template_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employment_history',
            new_name='EmploymentHistory',
        ),
    ]
