# Generated by Django 3.2.6 on 2021-08-16 12:20

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(null=True, upload_to='img/templates/')),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='templates/CV_Templates'), upload_to='')),
                ('css_file', models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location='static/css/cv_templates'), upload_to='')),
            ],
        ),
    ]
