# Generated by Django 3.2.6 on 2021-08-16 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_templates_template'),
        ('template_manager', '0002_templatestyle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Template',
        ),
    ]
