# Generated by Django 3.2.6 on 2021-10-27 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('template_manager', '0002_rename_employment_history_employmenthistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='user',
        ),
        migrations.RemoveField(
            model_name='employmenthistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='languages',
            name='user',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='user',
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='template_manager.education')),
                ('employment_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='template_manager.employmenthistory')),
                ('languages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='template_manager.languages')),
                ('personal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='template_manager.personalinfo')),
                ('skills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='template_manager.skills')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
