# Generated by Django 3.2.6 on 2021-08-11 09:57

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_manager', '0002_auto_20210811_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='css_file',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location='static/css/templates'), upload_to=''),
        ),
    ]
