# Generated by Django 3.2.6 on 2021-08-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_manager', '0003_delete_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatestyle',
            name='file',
        ),
        migrations.AlterField(
            model_name='templatestyle',
            name='image',
            field=models.ImageField(null=True, upload_to='img/cv_templates/'),
        ),
    ]
