# Generated by Django 3.2.6 on 2021-10-27 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('template_manager', '0003_auto_20211027_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='education',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='template_manager.education'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='employment_history',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='template_manager.employmenthistory'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='languages',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='template_manager.languages'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='personal_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='template_manager.personalinfo'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='template_manager.skills'),
        ),
    ]
