# Generated by Django 3.2.6 on 2021-08-13 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('template_manager', '0004_template_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='user',
        ),
    ]
