# Generated by Django 3.2.6 on 2021-10-29 21:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_manager', '0006_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='education',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None), size=None),
        ),
        migrations.AlterField(
            model_name='resume',
            name='emp_history',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None), size=None),
        ),
        migrations.AlterField(
            model_name='resume',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None), size=None),
        ),
        migrations.AlterField(
            model_name='resume',
            name='personal_info',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None), size=None),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None), size=None),
        ),
    ]
