# Generated by Django 3.2.6 on 2021-10-29 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_manager', '0006_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='education',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='resume',
            name='emp_history',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='resume',
            name='languages',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=models.TextField(),
        ),
    ]
