# Generated by Django 3.2.3 on 2021-08-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='template_selected',
            field=models.IntegerField(null=True),
        ),
    ]
