# Generated by Django 3.2.6 on 2021-08-16 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('template_manager', '0002_templatestyle'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_templates',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='template_manager.templatestyle'),
        ),
    ]
