# Generated by Django 3.2.6 on 2021-08-17 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_templates_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profiles/photo/')),
                ('first_name', models.CharField(max_length=20, null=True)),
                ('last_name', models.CharField(max_length=20, null=True)),
                ('occupation', models.CharField(max_length=30, null=True)),
                ('address', models.CharField(max_length=20, null=True)),
                ('city', models.CharField(max_length=20, null=True)),
                ('country', models.CharField(max_length=20, null=True)),
                ('phone', models.IntegerField()),
                ('about_me', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='user_templates',
            name='about_me',
        ),
        migrations.RemoveField(
            model_name='user_templates',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user_templates',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user_templates',
            name='country',
        ),
        migrations.RemoveField(
            model_name='user_templates',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user_templates',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user_templates',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='user_templates',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user_templates',
            name='photo',
        ),
        migrations.AddField(
            model_name='user_templates',
            name='personal_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.personalinfo'),
        ),
    ]
