# Generated by Django 3.2.6 on 2021-08-17 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210817_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_templates',
            name='personal_info',
        ),
    ]
