# Generated by Django 3.2.6 on 2021-10-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_template_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='number_of_saved_resumes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
